### ISSUE TITLE
sortof small fix 

### ISSUE THREAD

**Issue by loordgek** [MineMaarten/AdvancedMod#4]
https://github.com/loordgek/AdvancedMod/commit/d38dd58f3e56761b5c06ac0c68628ad26dc2d322

**Comment by MSourceCoded** [comment]
[Perhaps a pull request would fit better](https://www.youtube.com/watch?v=EC1Aegfjj50)

**Comment by MineMaarten** [comment]
That would be a solution to the problem that two actions are wanting to be mapped to right clicking. I don't know if it's the most logical for users however.. I dunno..
